## Import relevant libraries


In [1]:
import numpy as np 
import pandas as pd

## Load the data

In [2]:
data_preprocessed = pd.read_csv("df_preprocessed.csv")

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [4]:
### Logisitic regression will be applied on reasons , work transportation expenses , distance to work ,
### age , daily work load average , education , children and pets and will predict their Absenteeism

### The nice thing about regressions is that the model itself will give us a fair indication of which variables 
### are important for the analysis and which aren't


## Create the targets

In [5]:
# we will divide the categories of Absenteeism into : 1- Excessively Absent     2- Slightly Absent 
# This can be done by specifying the median , in which the values below it lies in the 2nd category and the values above it lies in the first 

data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
# Everyone who is absent above 3 hours , he is considered as excessively absent person 
# 0 : Moderately absent 
# 1 : Highly Absent 

targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >  data_preprocessed['Absenteeism Time in Hours'].median() ,1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
type(targets)

numpy.ndarray

In [9]:
type(data_preprocessed)

pandas.core.frame.DataFrame

In [10]:
data_preprocessed['Excessively Absent'] = targets

In [11]:
type(data_preprocessed['Excessively Absent'])

pandas.core.series.Series

In [12]:
data_preprocessed.head(15)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0          0         0         0         1            7                1   
1          0         0         0         0            7                1   
2          0         0         0         1            7                2   
3          1         0         0         0            7                3   
4          0         0         0         1            7                3   
5          0         0         0         1            7                4   
6          0         0         0         1            7                4   
7          0         0         0         1            7                4   
8          0         0         1         0            7                0   
9          0         0         0         1            7                0   
10         1         0         0         0            7                0   
11         1         0         0         0            7                1   
12         1         0         0         0            7                2   
13         1         0         0         0            7                2   
14         0         0         0         1            7                2   

    Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                      289                36   33                  239.554   
1                      118                13   50                  239.554   
2                      179                51   38                  239.554   
3                      279                 5   39                  239.554   
4                      289                36   33                  239.554   
5                      179                51   38                  239.554   
6                      361                52   28                  239.554   
7                      260                50   36                  239.554   
8                      155                12   34                  239.554   
9                      235                11   37                  239.554   
10                     260                50   36                  239.554   
11                     260                50   36                  239.554   
12                     260                50   36                  239.554   
13                     179                51   38                  239.554   
14                     179                51   38                  239.554   

    Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0                30          0         2     1                          4   
1                31          0         1     0                          0   
2                31          0         0     0                          2   
3                24          0         2     0                          4   
4                30          0         2     1                          2   
5                31          0         0     0                          2   
6                27          0         1     4                          8   
7                23          0         4     0                          4   
8                25          0         2     0                         40   
9                29          1         1     1                          8   
10               23          0         4     0                          8   
11               23          0         4     0                          8   
12               23          0         4     0                          8   
13               31          0         0     0                          1   
14               31          0         0     0                          4   

    Excessively Absent  
0                    1  
1                    0  
2                    0  
3                    1  
4                    0  
5                    0  
6                    1  
7                    1  
8                    1  
9                    1  
10                   1  
11   

### Using the median as we see , it's a rigid and simple technique to keep your dataset balanced around (50-50,60-40,and 55-45). Some techniques may accept like logistic regression with 60-40 classification; but NN techniques may decline 
#### 55-45 ratio is very sufficient 


In [13]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [14]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week', 'Daily Work Load Average', 'Distance to Work'], axis = 1)

In [15]:
# data_with_targets = data_preprocessed.copy() --> doesn't make them refer to the same object (even if they have the same columns numbers)

In [16]:
data_with_targets is data_preprocessed  #=> false because the new df has 1 column less than the original df

False

In [17]:
data_with_targets.head(10)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   
5         0         0         0         1            7   
6         0         0         0         1            7   
7         0         0         0         1            7   
8         0         0         1         0            7   
9         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   
5                     179   38               31          0         0     0   
6                     361   28               27          0         1     4   
7                     260   36               23          0         4     0   
8                     155   34               25          0         2     0   
9                     235   37               29          1         1     1   

   Excessively Absent  
0                   1  
1                   0  
2                   0  
3                   1  
4                   0  
5                   0  
6                   1  
7                   1  
8                   1  
9                   1

## Selecting the inputs with pandas iloc

In [18]:
data_with_targets.shape
#-> rows : 0 to 699 
#-> cols : 0 to 14 

(700, 12)

In [19]:
# to select the inputs for our regression we need to exclude the last column 
data_with_targets.iloc[:,:-1] #=> excludes the last 
#=> iloc[rows_range , columns_range]
#### the following has the same meaning ####
# 0 : 14 --> from 0 to 13 
# :14 --> from the beginning to 13 
# :-1 --> till the last columns (minus sign meaning the number of columns at end you want to skip)
# :shape[1]-1 --> same meaning

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [20]:
unscaled_inputs = data_with_targets.iloc[:,:-1] 
type(unscaled_inputs)

pandas.core.frame.DataFrame

## Standardize the data 

In [21]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler  = StandardScaler()

In [22]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):

        def __init__(self, columns):
            self.scaler = StandardScaler()
            self.columns = columns
            self.mean_ = None
            self.var_ = None
            
        def fit(self, X, y = None):
            self.scaler.fit(X[self.columns], y)
            self.mean_ = np.mean(X[self.columns], axis=1)
            self.var_ = np.var(X[self.columns])
            return self
        
        def transform(self, X, y = None, copy = None):
            init_col_order = X.columns
            X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns = self.columns)
            X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
            return pd.concat([X_not_scaled, X_scaled], axis = 1)[init_col_order]

In [23]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [59]:
columns_to_scale = ['Month Value','Transportation Expense',
          'Age',
            'Body Mass Index', 'Children', 'Pets']
# OR
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [60]:
# Custom scaler 
absenteeism_scaler = CustomScaler(columns_to_scale)


In [61]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [62]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)
type(scaled_inputs) # => sklearn results are ndarrays , so take care
# we subtract the mean and divide by standard deviation

pandas.core.frame.DataFrame

In [63]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [64]:
scaled_inputs.shape
# 700 observations , 14 features

(700, 11)

## Train-test data split 
##### When using the overfitting technique on all of our data and it gets exposed to new data , it fails miserably on this new data. One way to work it around is to split the data to train data for the machine to train on and work on it and the hidden (rest of the data) is used as a test to this machine model

## Import the relevant module

In [65]:
from sklearn.model_selection import train_test_split

## Split

In [66]:
train_test_split(scaled_inputs,targets, train_size = 0.8 , random_state = 20 )

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 346         0         0         0         1     1.610276   
 91          0         0         1         0     1.324766   
 299         1         0         0         0     1.039256   
 129         0         0         1         0    -1.530333   
 695         1         0         0         0    -0.388293   
 ..        ...       ...       ...       ...          ...   
 218         1         0         0         0    -0.388293   
 223         0         0         0         1    -0.102784   
 271         0         0         0         1     0.753746   
 474         0         0         0         1     0.182726   
 355         0         0         0         1     1.610276   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 346               -0.654143  0.248310         1.002633          0 -0.919030   
 91                -0.654143  0.562059        -1.114186          1  0.880469   
 299               -0.6541

In [67]:
x_train , x_test , y_train , y_test = train_test_split(scaled_inputs,targets, train_size = 0.8, random_state = 20) 
# train_size takes values between 0 and 1 
# shuffle parameter default is always true [but it doesn't imply robust accurate results]
# random states controls the shuffle a bit , setting it to 20 

In [68]:
print (x_train.shape , y_train.shape) # 75% by default split  but this is 80
# => they have the same observations but differ in feature numbers , Why ? 
# =>  because the y_train stands for one target which is the last column 

(560, 11) (560,)


In [69]:
print(x_test.shape , y_test.shape) # 25% by default split but this is 20%

(140, 11) (140,)


## Logistic regression with sci-kit learn

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics 

## Training the module 

In [71]:
log_reg = LogisticRegression()

In [72]:
log_reg.fit(x_train,y_train)

LogisticRegression()

In [73]:
log_reg.score(x_train,y_train) #=> accuracy 

0.7732142857142857

## Manually checking the accuracy

In [74]:
model_outputs = log_reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [75]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [91]:
sum(model_outputs == y_train)

433

In [77]:
# sum(y_train==model_outputs)/y_train.shape[0]
np.sum(y_train==model_outputs)/model_outputs.shape[0]

0.7732142857142857

## Finding the intercepts and coefficients

In [78]:
log_reg.intercept_   #=> [bias]

array([-1.6474549])

In [79]:
log_reg.coef_ #=> good values , but I need to map them back again to my own inputs [weight]

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [80]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [81]:
feature_name = unscaled_inputs.columns.values
# => It's a good idea to declare a new variable containing this information 

In [82]:
summary_table = pd.DataFrame(columns=['Feature name'], data = feature_name)
# we want to create this data frame - a neat one - to contain the intercepts , coef_ and their corresponding feature names

In [83]:
summary_table['Coefficients'] = np.transpose(log_reg.coef_)
# by default  ,nd arrays are rows 
summary_table

Feature name  Coefficients
0                 Reason_1      2.800197
1                 Reason_2      0.951884
2                 Reason_3      3.115553
3                 Reason_4      0.839001
4              Month Value      0.158930
5   Transportation Expense      0.605284
6                      Age     -0.169891
7          Body Mass Index      0.279811
8                Education     -0.210533
9                 Children      0.348262
10                    Pets     -0.277396

In [84]:
summary_table.index = summary_table.index + 1 #=> shifts the dataframe data one down , leaving index 0 empty (not seen but it's there)


In [85]:
summary_table.loc[0] = ['Intercept',log_reg.intercept_[0]] # fills in the 0 index with desired tuple [at the end]


In [86]:
summary_table = summary_table.sort_index() # sort the 0 since the added index is formed at the end of the dataFrame
summary_table

Feature name  Coefficients
0                Intercept     -1.647455
1                 Reason_1      2.800197
2                 Reason_2      0.951884
3                 Reason_3      3.115553
4                 Reason_4      0.839001
5              Month Value      0.158930
6   Transportation Expense      0.605284
7                      Age     -0.169891
8          Body Mass Index      0.279811
9                Education     -0.210533
10                Children      0.348262
11                    Pets     -0.277396

## Interpreting the coefficients and intercepts 


In [87]:
summary_table['Odd Ratio'] = np.exp(summary_table.Coefficients)
# log(Odds) = bias + coef1*feature1 + ..... 
# Odds = exp el kalam eli fo2 da 
summary_table

Feature name  Coefficients  Odd Ratio
0                Intercept     -1.647455   0.192539
1                 Reason_1      2.800197  16.447892
2                 Reason_2      0.951884   2.590585
3                 Reason_3      3.115553  22.545903
4                 Reason_4      0.839001   2.314054
5              Month Value      0.158930   1.172256
6   Transportation Expense      0.605284   1.831773
7                      Age     -0.169891   0.843757
8          Body Mass Index      0.279811   1.322880
9                Education     -0.210533   0.810152
10                Children      0.348262   1.416604
11                    Pets     -0.277396   0.757754

In [88]:
summary_table = summary_table.sort_values('Odd Ratio' , ascending=False)

In [89]:
summary_table #=> listed from most important down to least important 
# Now we get insight of features that makes no difference 
# features with coefficients around 0 ~ features with odd ratio around 1 -> both ineffective 

Feature name  Coefficients  Odd Ratio
3                 Reason_3      3.115553  22.545903
1                 Reason_1      2.800197  16.447892
2                 Reason_2      0.951884   2.590585
4                 Reason_4      0.839001   2.314054
6   Transportation Expense      0.605284   1.831773
10                Children      0.348262   1.416604
8          Body Mass Index      0.279811   1.322880
5              Month Value      0.158930   1.172256
7                      Age     -0.169891   0.843757
9                Education     -0.210533   0.810152
11                    Pets     -0.277396   0.757754
0                Intercept     -1.647455   0.192539

In [90]:
# NOT YET UNDERSTANDED 
# for a unit change in a standardized feature , the odd increase by a multiple equal to that of the odd ratio 
# Omitting reason 0 makes it a base model (3la ma yabdo enna bn-compare beh)
# Standardizing dummies is bad  
# Same order in video , different number

# UNDERSTOOD 
# odds : p(x) / 1 - p(x) 
# odds ratio : comparing the odds of two features (odds(reason 3) / odds(reason 0))
# Why not standardize dummies ? because standardization puts the data between 0 and 1, dummies are already satisfying this category 
# log(odds) = bias + coef1*feature1 + ..... --> log(odds) = log(p(x) / 1 - p(x)) = bias + coef1*feature1 + ..... => linear regression
# odds = exp(bias + coef1*feature1 + .....) => logistic regression


## Interpretation of the upper summary table and drawbacks of standardizations 
### Daily Work Load Average , Distance to Work and Day of the Week have less impact as they approach 0 
### Features with positive Coefficients (Higher Odd Ratio) Implies the higher chances of absenteeism 
##### Ex: Reason 3 , a poisoned person , has of course 20x chances for absence (No shit sherlock !) 
##### Ex: A person with a huge number of pets has a meaning that he has someone to help with so his chances of absenteeism fall back 
### We call the intercept a calibrating factor (bias) for the model to ensure good, accurate results , it has no interpreting meaning to its value 

## Drawbacks of Standardization 
### Lacks Interpretations meaning (statisticans) , but Accuracy makes it up for it (programmers)

## Backward Elimination : Removal of non-effective features after seeing their coefficients (Odd Ratios) 

In [ ]:
#############################################################################################################################

## Testing the model 

In [93]:
log_reg.score(x_test,y_test)

0.75

In [96]:
predicted_proba = log_reg.predict_proba(x_test)
predicted_proba
#=> will all sum to 1 

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [98]:
predicted_proba[:,1]
# if >0.5 , put 1 , else 0 


array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

## Saving the model

In [99]:
import pickle

In [101]:
with open('model', 'wb') as file:
    pickle.dump(log_reg,file)

    # 'rb' -> read byte 
    # 'load' x 'dump'
    # 'model' refers to ml model after being trained

In [102]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)
    
# we need to preprocess any new data with the same rules 